apiVersion: v2
name: kube-state-metrics
description: Install kube-state-metrics to generate and expose cluster-level metrics
keywords:
- metric
- monitoring
- prometheus
- kubernetes
type: application
version: 3.0.0
appVersion: 2.0.0-beta
home: https://github.com/kubernetes/kube-state-metrics/
sources:
- https://github.com/kubernetes/kube-state-metrics/
maintainers:
- name: tariq1890
  email: tariq.ibrahim@mulesoft.com
- name: mrueg
  email: manuel@rueg.eu
