{{- if .Values.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kube-state-metrics.fullname" . }}
  namespace: {{ template "kube-state-metrics.namespace" . }}
  labels:
    app: {{ template "kube-state-metrics.name" . }}
{{- include "kube-state-metrics.labels" . | indent 4 }}
    {{- if .Values.prometheus.monitor.additionalLabels }}
{{ toYaml .Values.prometheus.monitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kube-state-metrics.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      {{- if .Values.prometheus.monitor.honorLabels }}
      honorLabels: true
      {{- end }}
    {{ if .Values.selfMonitor.enabled }}
    - port: metrics
      {{- if .Values.prometheus.monitor.honorLabels }}
      honorLabels: true
      {{- end }}
    {{ end }}
{{- end }}
