commonLabels:
  app.kubernetes.io/name: kube-state-metrics

namespace: kube-system

resources:
- kube-state-metrics-cluster-role-binding.yaml
- kube-state-metrics-cluster-role.yaml
- kube-state-metrics-deployment.yaml
- kube-state-metrics-role-binding.yaml
- kube-state-metrics-role.yaml
- kube-state-metrics-service-account.yaml
- kube-state-metrics-service.yaml
