name: openvex

on:
  workflow_dispatch:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  vexctl:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Set environment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: openvex/generate-vex@c59881b41451d7ccba5c3b74cd195382b8971fcd
        # Refer: https://github.com/openvex/vexctl#operational-model
        name: Run vexctl
        with:
            product: pkg:golang/k8s.io/kube-state-metrics/v2@${{ env.RELEASE_VERSION }}
            file: kube-state-metrics.openvex.json

      - name: Upload OpenVEX document to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ env.RELEASE_VERSION }} kube-state-metrics.openvex.json
